"""descripcion_del_cambio

Revision ID: 215229186fae
Revises: 726611a4690b
Create Date: 2026-07-26 23:14:50.541344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '215229186fae'
down_revision: Union[str, Sequence[str], None] = '726611a4690b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_actividades_fecha'), 'actividades', ['fecha'], unique=False)
    op.create_index(op.f('ix_actividades_tipo_actividad'), 'actividades', ['tipo_actividad'], unique=False)
    op.create_index(op.f('ix_actividades_lectura_cperfac'), 'actividades_lectura', ['cperfac'], unique=False)
    op.add_column('alertas', sa.Column('fecha', sa.Date(), nullable=False))
    op.drop_constraint(op.f('uq_alerta_ccodprs_kpi_fecha'), 'alertas', type_='unique')
    op.create_unique_constraint('uq_alerta_ccodprs_kpi_fecha', 'alertas', ['ccodprs', 'kpi', 'fecha'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_alerta_ccodprs_kpi_fecha', 'alertas', type_='unique')
    op.create_unique_constraint(op.f('uq_alerta_ccodprs_kpi_fecha'), 'alertas', ['ccodprs', 'kpi', 'fecha_generacion'], postgresql_nulls_not_distinct=False)
    op.drop_column('alertas', 'fecha')
    op.drop_index(op.f('ix_actividades_lectura_cperfac'), table_name='actividades_lectura')
    op.drop_index(op.f('ix_actividades_tipo_actividad'), table_name='actividades')
    op.drop_index(op.f('ix_actividades_fecha'), table_name='actividades')
    # ### end Alembic commands ###
