"""agregar campos

Revision ID: 3b862c343b93
Revises: 95a0a53408bb
Create Date: 2026-07-25 17:49:15.999045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b862c343b93'
down_revision: Union[str, Sequence[str], None] = '95a0a53408bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trabajadores', sa.Column('telefono', sa.String(), nullable=True))
    op.drop_column('trabajadores', 'supervisor')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trabajadores', sa.Column('supervisor', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('trabajadores', 'telefono')
    # ### end Alembic commands ###
