"""agregar_nuevas_variables

Revision ID: 4765d852fea3
Revises: b92d88e0aad3
Create Date: 2026-07-29 04:00:21.851807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4765d852fea3'
down_revision: Union[str, Sequence[str], None] = 'b92d88e0aad3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ordenes_corte',
    sa.Column('id_orden', sa.Integer(), nullable=False),
    sa.Column('ccodprg', sa.String(length=30), nullable=False),
    sa.Column('dgenprg', sa.Date(), nullable=True),
    sa.Column('cmetfac', sa.String(length=10), nullable=True),
    sa.Column('ctipprg', sa.Integer(), nullable=True),
    sa.Column('ccodcnx', sa.String(length=20), nullable=False),
    sa.Column('cnromdr', sa.String(length=30), nullable=True),
    sa.Column('ntotdeu', sa.Float(), nullable=True),
    sa.Column('nmesdeu', sa.Integer(), nullable=True),
    sa.Column('dejecuc', sa.Date(), nullable=True),
    sa.Column('nleccor', sa.Integer(), nullable=True),
    sa.Column('cimpcrp', sa.String(length=10), nullable=True),
    sa.Column('cobscrp', sa.String(length=255), nullable=True),
    sa.Column('csitreg', sa.String(length=5), nullable=True),
    sa.Column('ccodacc', sa.String(length=10), nullable=True),
    sa.Column('cdesacc', sa.String(), nullable=True),
    sa.Column('hora', sa.Integer(), nullable=True),
    sa.Column('minuto', sa.Integer(), nullable=True),
    sa.Column('segundo', sa.Integer(), nullable=True),
    sa.Column('cutmx', sa.Float(), nullable=True),
    sa.Column('cutmy', sa.Float(), nullable=True),
    sa.Column('direccion', sa.String(), nullable=True),
    sa.Column('categoria', sa.String(length=50), nullable=True),
    sa.Column('distrito', sa.String(length=100), nullable=True),
    sa.Column('id_carga', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ccodcnx'], ['conexiones.ccodcnx'], ),
    sa.ForeignKeyConstraint(['id_carga'], ['registros_carga.id_carga'], ),
    sa.PrimaryKeyConstraint('id_orden')
    )
    op.create_index(op.f('ix_ordenes_corte_ccodcnx'), 'ordenes_corte', ['ccodcnx'], unique=False)
    op.create_index(op.f('ix_ordenes_corte_ccodprg'), 'ordenes_corte', ['ccodprg'], unique=False)
    op.create_index(op.f('ix_ordenes_corte_cmetfac'), 'ordenes_corte', ['cmetfac'], unique=False)
    op.create_index(op.f('ix_ordenes_corte_csitreg'), 'ordenes_corte', ['csitreg'], unique=False)
    op.create_index(op.f('ix_ordenes_corte_dejecuc'), 'ordenes_corte', ['dejecuc'], unique=False)
    op.create_index(op.f('ix_ordenes_corte_distrito'), 'ordenes_corte', ['distrito'], unique=False)
    op.create_index(op.f('ix_ordenes_corte_id_orden'), 'ordenes_corte', ['id_orden'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ordenes_corte_id_orden'), table_name='ordenes_corte')
    op.drop_index(op.f('ix_ordenes_corte_distrito'), table_name='ordenes_corte')
    op.drop_index(op.f('ix_ordenes_corte_dejecuc'), table_name='ordenes_corte')
    op.drop_index(op.f('ix_ordenes_corte_csitreg'), table_name='ordenes_corte')
    op.drop_index(op.f('ix_ordenes_corte_cmetfac'), table_name='ordenes_corte')
    op.drop_index(op.f('ix_ordenes_corte_ccodprg'), table_name='ordenes_corte')
    op.drop_index(op.f('ix_ordenes_corte_ccodcnx'), table_name='ordenes_corte')
    op.drop_table('ordenes_corte')
    # ### end Alembic commands ###
