"""cambios en mis modelos

Revision ID: 545c2b144d7d
Revises: f08ed5565395
Create Date: 2026-07-20 00:02:46.970483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '545c2b144d7d'
down_revision: Union[str, Sequence[str], None] = 'f08ed5565395'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intervenciones',
    sa.Column('id_intervencion', sa.Integer(), nullable=False),
    sa.Column('alerta_id', sa.String(), nullable=True),
    sa.Column('supervisor_id', sa.String(), nullable=True),
    sa.Column('fecha_accion', sa.DateTime(), nullable=True),
    sa.Column('accion_tomada', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['alerta_id'], ['alertas.alerta_id'], ),
    sa.ForeignKeyConstraint(['supervisor_id'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_intervencion')
    )
    op.add_column('actividades', sa.Column('cmetfac', sa.String(length=10), nullable=False))
    op.add_column('alertas', sa.Column('comentario_resolucion', sa.Text(), nullable=True))
    op.add_column('alertas', sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alertas', 'fecha_actualizacion')
    op.drop_column('alertas', 'comentario_resolucion')
    op.drop_column('actividades', 'cmetfac')
    op.drop_table('intervenciones')
    # ### end Alembic commands ###
