"""agregar_nuevas_variables

Revision ID: 5cdfa4d42094
Revises: 215229186fae
Create Date: 2026-07-28 18:34:13.280688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cdfa4d42094'
down_revision: Union[str, Sequence[str], None] = '215229186fae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actividades', sa.Column('id_carga', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'actividades', 'registros_carga', ['id_carga'], ['id_carga'])
    op.add_column('resumen_diario_lector', sa.Column('id_carga', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'resumen_diario_lector', 'registros_carga', ['id_carga'], ['id_carga'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'resumen_diario_lector', type_='foreignkey')
    op.drop_column('resumen_diario_lector', 'id_carga')
    op.drop_constraint(None, 'actividades', type_='foreignkey')
    op.drop_column('actividades', 'id_carga')
    # ### end Alembic commands ###
