"""init_clean_models

Revision ID: 6600bd692ec9
Revises: 
Create Date: 2026-07-19 05:46:35.189643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6600bd692ec9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalogo_impedimentos',
    sa.Column('codigo', sa.String(length=10), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=False),
    sa.Column('categoria', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('codigo')
    )
    op.create_table('catalogo_observaciones',
    sa.Column('codigo', sa.String(length=10), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('codigo')
    )
    op.create_table('rutas',
    sa.Column('ruta_id', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('ruta_id')
    )
    op.create_table('trabajadores',
    sa.Column('ccodprs', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('distrito_base', sa.String(), nullable=True),
    sa.Column('supervisor', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('ccodprs')
    )
    op.create_table('usuarios',
    sa.Column('id_usuario', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('correo', sa.String(), nullable=False),
    sa.Column('rol', sa.String(), nullable=False),
    sa.Column('estado', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    op.create_index(op.f('ix_usuarios_correo'), 'usuarios', ['correo'], unique=True)
    op.create_index(op.f('ix_usuarios_id_usuario'), 'usuarios', ['id_usuario'], unique=False)
    op.create_table('zonas',
    sa.Column('zona_id', sa.String(), nullable=False),
    sa.Column('distrito', sa.String(length=100), nullable=False),
    sa.Column('zona_operativa', sa.String(), nullable=True),
    sa.Column('cuadrante', sa.String(), nullable=True),
    sa.Column('cmetfac', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('zona_id')
    )
    op.create_table('alertas',
    sa.Column('alerta_id', sa.String(), nullable=False),
    sa.Column('nivel', sa.String(), nullable=False),
    sa.Column('kpi', sa.String(), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=False),
    sa.Column('fecha_generacion', sa.DateTime(), nullable=True),
    sa.Column('estado_alerta', sa.String(), nullable=True),
    sa.Column('zona_id', sa.String(), nullable=True),
    sa.Column('ccodprs', sa.String(length=20), nullable=True),
    sa.Column('supervisor_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['ccodprs'], ['trabajadores.ccodprs'], ),
    sa.ForeignKeyConstraint(['supervisor_id'], ['usuarios.id_usuario'], ),
    sa.ForeignKeyConstraint(['zona_id'], ['zonas.zona_id'], ),
    sa.PrimaryKeyConstraint('alerta_id')
    )
    op.create_table('conexiones',
    sa.Column('ccodcnx', sa.String(length=20), nullable=False),
    sa.Column('cnromdr', sa.String(length=30), nullable=True),
    sa.Column('zona_id', sa.String(), nullable=True),
    sa.Column('ruta_id', sa.String(), nullable=True),
    sa.Column('direccion_ref', sa.String(), nullable=True),
    sa.Column('tipo_conexion', sa.String(), nullable=True),
    sa.Column('estado_servicio', sa.String(), nullable=True),
    sa.Column('latitud_real', sa.Float(), nullable=True),
    sa.Column('longitud_real', sa.Float(), nullable=True),
    sa.Column('utm_x', sa.Float(), nullable=True),
    sa.Column('utm_y', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['ruta_id'], ['rutas.ruta_id'], ),
    sa.ForeignKeyConstraint(['zona_id'], ['zonas.zona_id'], ),
    sa.PrimaryKeyConstraint('ccodcnx')
    )
    op.create_table('registros_carga',
    sa.Column('id_carga', sa.Integer(), nullable=False),
    sa.Column('nombre_archivo', sa.String(), nullable=False),
    sa.Column('fecha_carga', sa.DateTime(), nullable=True),
    sa.Column('proceso', sa.String(), nullable=False),
    sa.Column('registros_insertados', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_carga')
    )
    op.create_index(op.f('ix_registros_carga_id_carga'), 'registros_carga', ['id_carga'], unique=False)
    op.create_table('actividades',
    sa.Column('actividad_id', sa.String(), nullable=False),
    sa.Column('ccodcnx', sa.String(length=20), nullable=True),
    sa.Column('ccodprs', sa.String(length=20), nullable=True),
    sa.Column('tipo_actividad', sa.String(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('hora_inicio', sa.DateTime(), nullable=True),
    sa.Column('hora_fin', sa.DateTime(), nullable=True),
    sa.Column('duracion_min', sa.Float(), nullable=True),
    sa.Column('duracion_esperada_min', sa.Float(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('resultado', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['ccodcnx'], ['conexiones.ccodcnx'], ),
    sa.ForeignKeyConstraint(['ccodprs'], ['trabajadores.ccodprs'], ),
    sa.PrimaryKeyConstraint('actividad_id')
    )
    op.create_table('actividades_lectura',
    sa.Column('actividad_id', sa.String(), nullable=False),
    sa.Column('dlectur', sa.DateTime(), nullable=True),
    sa.Column('nlecact', sa.Integer(), nullable=True),
    sa.Column('cimplec', sa.String(length=10), nullable=True),
    sa.Column('cobsmdr', sa.String(length=255), nullable=True),
    sa.Column('cgpsalt', sa.Float(), nullable=True),
    sa.Column('cgpslat', sa.Float(), nullable=True),
    sa.Column('cgpslon', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['actividad_id'], ['actividades.actividad_id'], ),
    sa.PrimaryKeyConstraint('actividad_id')
    )
    op.create_table('impedimentos',
    sa.Column('impedimento_id', sa.String(), nullable=False),
    sa.Column('actividad_id', sa.String(), nullable=True),
    sa.Column('cimplec', sa.String(length=10), nullable=True),
    sa.Column('categoria', sa.String(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('cgpslat', sa.Float(), nullable=True),
    sa.Column('cgpslon', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['actividad_id'], ['actividades.actividad_id'], ),
    sa.PrimaryKeyConstraint('impedimento_id')
    )
    op.create_table('observaciones',
    sa.Column('observacion_id', sa.String(), nullable=False),
    sa.Column('actividad_id', sa.String(), nullable=True),
    sa.Column('codigo', sa.String(length=10), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['actividad_id'], ['actividades.actividad_id'], ),
    sa.PrimaryKeyConstraint('observacion_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('observaciones')
    op.drop_table('impedimentos')
    op.drop_table('actividades_lectura')
    op.drop_table('actividades')
    op.drop_index(op.f('ix_registros_carga_id_carga'), table_name='registros_carga')
    op.drop_table('registros_carga')
    op.drop_table('conexiones')
    op.drop_table('alertas')
    op.drop_table('zonas')
    op.drop_index(op.f('ix_usuarios_id_usuario'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_correo'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('trabajadores')
    op.drop_table('rutas')
    op.drop_table('catalogo_observaciones')
    op.drop_table('catalogo_impedimentos')
    # ### end Alembic commands ###
