"""agregar_tipo_archivo_a_registros_carga

Revision ID: 726611a4690b
Revises: 3b862c343b93
Create Date: 2026-07-26 15:23:46.975372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '726611a4690b'
down_revision: Union[str, Sequence[str], None] = '3b862c343b93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalogo_grupos_facturacion',
    sa.Column('cmetfac', sa.String(length=10), nullable=False),
    sa.Column('ccodmet', sa.String(length=10), nullable=True),
    sa.Column('cnommet', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('cmetfac')
    )
    op.create_table('evaluaciones_desempeno',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ccodprs', sa.String(length=20), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('puntaje', sa.Float(), nullable=False),
    sa.Column('clasificacion', sa.String(length=30), nullable=False),
    sa.Column('tendencia', sa.String(length=20), nullable=True),
    sa.Column('eficiencia', sa.Float(), nullable=True),
    sa.Column('cumplimiento', sa.Float(), nullable=True),
    sa.Column('productividad', sa.Float(), nullable=True),
    sa.Column('impedimentos', sa.Float(), nullable=True),
    sa.Column('observaciones', sa.Float(), nullable=True),
    sa.Column('cobertura', sa.Float(), nullable=True),
    sa.Column('motivos', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['ccodprs'], ['trabajadores.ccodprs'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluaciones_desempeno_id'), 'evaluaciones_desempeno', ['id'], unique=False)
    op.create_table('kpi_diario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('zona_id', sa.String(), nullable=True),
    sa.Column('kpi_nombre', sa.String(), nullable=False),
    sa.Column('numerador', sa.Float(), nullable=True),
    sa.Column('denominador', sa.Float(), nullable=True),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('nivel_alerta', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['zona_id'], ['zonas.zona_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fecha', 'zona_id', 'kpi_nombre', name='uq_kpi_diario_fecha_zona_kpi')
    )
    op.create_index(op.f('ix_kpi_diario_id'), 'kpi_diario', ['id'], unique=False)
    op.create_table('resumen_diario_lector',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ccodprs', sa.String(length=20), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('cantidad_lecturas', sa.Integer(), nullable=True),
    sa.Column('lecturas_realizadas', sa.Integer(), nullable=True),
    sa.Column('lecturas_pendientes', sa.Integer(), nullable=True),
    sa.Column('cantidad_impedimentos', sa.Integer(), nullable=True),
    sa.Column('cantidad_observaciones', sa.Integer(), nullable=True),
    sa.Column('cantidad_fotos', sa.Integer(), nullable=True),
    sa.Column('ruta_id', sa.String(length=50), nullable=True),
    sa.Column('cmetfac', sa.String(length=10), nullable=True),
    sa.Column('fecha_inicio', sa.Date(), nullable=True),
    sa.Column('hora_inicio', sa.DateTime(), nullable=True),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('hora_fin', sa.DateTime(), nullable=True),
    sa.Column('duracion_total_min', sa.Float(), nullable=True),
    sa.Column('promedio_min', sa.Float(), nullable=True),
    sa.Column('eficiencia', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['ccodprs'], ['trabajadores.ccodprs'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ccodprs', 'fecha', name='uq_resumen_diario_lector_ccodprs_fecha')
    )
    op.create_index(op.f('ix_resumen_diario_lector_id'), 'resumen_diario_lector', ['id'], unique=False)
    op.add_column('actividades', sa.Column('distancia_metros', sa.Float(), nullable=True))
    op.drop_column('actividades', 'lecturas_realizadas')
    op.drop_column('actividades', 'eficiencia')
    op.drop_column('actividades', 'lecturas_pendientes')
    op.drop_column('actividades', 'lecturas_programadas')
    op.add_column('alertas', sa.Column('prioridad', sa.String(), nullable=True))
    op.create_unique_constraint('uq_alerta_ccodprs_kpi_fecha', 'alertas', ['ccodprs', 'kpi', 'fecha_generacion'])
    op.add_column('registros_carga', sa.Column('tipo_archivo', sa.String(), nullable=False))
    op.add_column('registros_carga', sa.Column('estado', sa.String(), nullable=False))
    op.add_column('registros_carga', sa.Column('registros_error', sa.Integer(), nullable=False))
    op.add_column('registros_carga', sa.Column('detalle_errores', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('registros_carga', 'detalle_errores')
    op.drop_column('registros_carga', 'registros_error')
    op.drop_column('registros_carga', 'estado')
    op.drop_column('registros_carga', 'tipo_archivo')
    op.drop_constraint('uq_alerta_ccodprs_kpi_fecha', 'alertas', type_='unique')
    op.drop_column('alertas', 'prioridad')
    op.add_column('actividades', sa.Column('lecturas_programadas', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('actividades', sa.Column('lecturas_pendientes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('actividades', sa.Column('eficiencia', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('actividades', sa.Column('lecturas_realizadas', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('actividades', 'distancia_metros')
    op.drop_index(op.f('ix_resumen_diario_lector_id'), table_name='resumen_diario_lector')
    op.drop_table('resumen_diario_lector')
    op.drop_index(op.f('ix_kpi_diario_id'), table_name='kpi_diario')
    op.drop_table('kpi_diario')
    op.drop_index(op.f('ix_evaluaciones_desempeno_id'), table_name='evaluaciones_desempeno')
    op.drop_table('evaluaciones_desempeno')
    op.drop_table('catalogo_grupos_facturacion')
    # ### end Alembic commands ###
