"""Agregar ccodprs y relacion a OrdenCorte

Revision ID: 8746d90452a7
Revises: 87b41a5b8ac1
Create Date: 2026-08-10 21:20:23.375745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8746d90452a7'
down_revision: Union[str, Sequence[str], None] = '87b41a5b8ac1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ordenes_corte', sa.Column('ccodprs', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_ordenes_corte_ccodprs'), 'ordenes_corte', ['ccodprs'], unique=False)
    op.create_foreign_key(None, 'ordenes_corte', 'trabajadores', ['ccodprs'], ['ccodprs'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ordenes_corte', type_='foreignkey')
    op.drop_index(op.f('ix_ordenes_corte_ccodprs'), table_name='ordenes_corte')
    op.drop_column('ordenes_corte', 'ccodprs')
    # ### end Alembic commands ###
