"""Agregar ccodprs y relacion a OrdenCorte

Revision ID: 87b41a5b8ac1
Revises: d08fb62d8910
Create Date: 2026-08-10 20:47:45.405492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87b41a5b8ac1'
down_revision: Union[str, Sequence[str], None] = 'd08fb62d8910'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
