"""agregar campos catastrales

Revision ID: 8bb81c14de84
Revises: f2bbecea98d2
Create Date: 2026-07-22 05:56:18.007265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bb81c14de84'
down_revision: Union[str, Sequence[str], None] = 'f2bbecea98d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actividades_lectura', sa.Column('cperfac', sa.String(length=10), nullable=True))
    op.drop_column('catalogo_impedimentos', 'categoria')
    op.add_column('conexiones', sa.Column('direccion', sa.String(), nullable=True))
    op.add_column('conexiones', sa.Column('categoria', sa.String(length=50), nullable=True))
    op.add_column('conexiones', sa.Column('condicion', sa.String(length=50), nullable=True))
    op.drop_column('conexiones', 'direccion_ref')
    op.drop_column('conexiones', 'tipo_conexion')
    op.drop_column('conexiones', 'estado_servicio')
    op.drop_column('trabajadores', 'distrito_base')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trabajadores', sa.Column('distrito_base', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('conexiones', sa.Column('estado_servicio', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('conexiones', sa.Column('tipo_conexion', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('conexiones', sa.Column('direccion_ref', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('conexiones', 'condicion')
    op.drop_column('conexiones', 'categoria')
    op.drop_column('conexiones', 'direccion')
    op.add_column('catalogo_impedimentos', sa.Column('categoria', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('actividades_lectura', 'cperfac')
    # ### end Alembic commands ###
