"""agregar campos

Revision ID: 95a0a53408bb
Revises: 8bb81c14de84
Create Date: 2026-07-25 15:16:33.320132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95a0a53408bb'
down_revision: Union[str, Sequence[str], None] = '8bb81c14de84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actividades', sa.Column('promedio_lectura', sa.Float(), nullable=True))
    op.add_column('actividades', sa.Column('lecturas_programadas', sa.Integer(), nullable=True))
    op.add_column('actividades', sa.Column('lecturas_realizadas', sa.Integer(), nullable=True))
    op.add_column('actividades', sa.Column('lecturas_pendientes', sa.Integer(), nullable=True))
    op.add_column('actividades', sa.Column('eficiencia', sa.Float(), nullable=True))
    op.add_column('alertas', sa.Column('valor_actual', sa.Float(), nullable=True))
    op.add_column('alertas', sa.Column('valor_umbral', sa.Float(), nullable=True))
    op.add_column('trabajadores', sa.Column('ultimo_puntaje', sa.Float(), nullable=True))
    op.add_column('trabajadores', sa.Column('ultima_clasificacion', sa.String(length=30), nullable=True))
    op.add_column('trabajadores', sa.Column('fecha_ultima_evaluacion', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trabajadores', 'fecha_ultima_evaluacion')
    op.drop_column('trabajadores', 'ultima_clasificacion')
    op.drop_column('trabajadores', 'ultimo_puntaje')
    op.drop_column('alertas', 'valor_umbral')
    op.drop_column('alertas', 'valor_actual')
    op.drop_column('actividades', 'eficiencia')
    op.drop_column('actividades', 'lecturas_pendientes')
    op.drop_column('actividades', 'lecturas_realizadas')
    op.drop_column('actividades', 'lecturas_programadas')
    op.drop_column('actividades', 'promedio_lectura')
    # ### end Alembic commands ###
