"""descripcion_de_tus_cambios

Revision ID: d08fb62d8910
Revises: 4765d852fea3
Create Date: 2026-07-30 22:07:16.611630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd08fb62d8910'
down_revision: Union[str, Sequence[str], None] = '4765d852fea3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('contrasena_hash', sa.String(), nullable=True))
    op.add_column('usuarios', sa.Column('proveedor', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'proveedor')
    op.drop_column('usuarios', 'contrasena_hash')
    # ### end Alembic commands ###
