"""add_utm_to_actividad_lectura

Revision ID: f08ed5565395
Revises: 126dbe1c0041
Create Date: 2026-07-19 07:17:08.856482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f08ed5565395'
down_revision: Union[str, Sequence[str], None] = '126dbe1c0041'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actividades_lectura', sa.Column('cutmx', sa.Float(), nullable=True))
    op.add_column('actividades_lectura', sa.Column('cutmy', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('actividades_lectura', 'cutmy')
    op.drop_column('actividades_lectura', 'cutmx')
    # ### end Alembic commands ###
